name: GenDocsGPT

run-name: ${{ github.actor }} is generating API docs for ${{ github.event.head_commit.message }} ${{ github.pull_request.user.email}}

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  genDocsGPT:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"

      - name: Install pip and run genDocsGPT
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install genDocsGPT
          

      - name: Create pull request with docs generated
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${{ github.actor }}@genDocsGPT.com"
          git config --global user.name "${{ github.actor }}"
          git checkout -b docs-generated-new
          git add .
          git commit -m "chore: API Documenation generated"
          git push -u origin docs-generated-new
          gh pr create --title "API Docs generated" --body "Pull request created by genDocsGPT GitHub Action"
