name: GenDocsGPT

run-name: ${{ github.actor }} is generating API docs

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  genDocsGPT:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      - name: Install pip and run genDocsGPT
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install genDocsGPT
          python3 -m genDocsGPT -v -m ./models -a ./gin -t ${{ secrets.ChatGPT_API_KEY}}

      - name: Create pull request with docs generated
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${{ github.actor }}@genDocsGPT.com"
          git config --global user.name "${{ github.actor }}"
          git checkout -b docs-generated-2
          git add .
          git commit -m "chore: API Documenation generated by genDocsGPT"
          git push -u origin docs-generated-2
          gh pr create --title "API Docs generated" --body "Pull request created by genDocsGPT GitHub Action"
